### ISSUE TITLE
Reproducing OGB submission

### ISSUE THREAD

**Issue by weihua916** [RBrossard/GINEPLUS#1]
Thank you for your leaderboard submission. Could you specify the command and hyper-parameters to reproduce your OGB leaderboard submission? A recommended `README` example is [here](https://github.com/PaddlePaddle/PGL/tree/main/ogb_examples/nodeproppred/unimp). I will update the leaderboard once this is done.

Thanks,
Weihua -- OGB Team

**Comment by RBrossard** [comment]
Thank you very much for your great work, it was extremely useful to us. I updated the README with a specific paragraph on how to reproduce the results on ogbg-molpcba, with a script in case you want to reproduce the statistics. Is it clear enough ?

Thanks,
Rémy Brossard -- AnotherBrain

**Comment by weihua916** [comment]
Thank you! Yes, it is very clear now, and the leaderboard has been updated.
